// <auto-generated />
using System;
using BudgetControl.Infrastructure.EF.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetControl.Migrations.Migrations
{
    [DbContext(typeof(BudgetControlDbContext))]
    [Migration("20251226004340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetControl.Domain.Aggregates.BudgetCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FundingSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FundingSourceId");

                    b.ToTable("budget_cycles", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Domain.Categories.SpendingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("spending_categories", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Domain.Entities.FundingSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("funding_sources", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Domain.Aggregates.BudgetCycle", b =>
                {
                    b.HasOne("BudgetControl.Domain.Entities.FundingSource", "Source")
                        .WithMany()
                        .HasForeignKey("FundingSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetControl.Domain.ValueObjects.Money", "TotalCapacity", b1 =>
                        {
                            b1.Property<Guid>("BudgetCycleId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_capacity");

                            b1.HasKey("BudgetCycleId");

                            b1.ToTable("budget_cycles");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCycleId");
                        });

                    b.OwnsMany("BudgetControl.Domain.Entities.DayAllocation", "Days", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BudgetCycleId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("boolean")
                                .HasColumnName("is_closed");

                            b1.HasKey("Id");

                            b1.HasIndex("BudgetCycleId");

                            b1.ToTable("day_allocations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BudgetCycleId");

                            b1.OwnsMany("BudgetControl.Domain.Entities.PartialExpense", "Expenses", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("CreatedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("user_id");

                                    b2.Property<Guid>("DayAllocationId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(600)
                                        .HasColumnType("character varying(600)")
                                        .HasColumnName("description");

                                    b2.Property<Guid>("SpendingCategoryId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("DayAllocationId");

                                    b2.HasIndex("SpendingCategoryId");

                                    b2.ToTable("partial_expenses", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("DayAllocationId");

                                    b2.HasOne("BudgetControl.Domain.Categories.SpendingCategory", "Category")
                                        .WithMany()
                                        .HasForeignKey("SpendingCategoryId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.OwnsOne("BudgetControl.Domain.ValueObjects.Money", "Amount", b3 =>
                                        {
                                            b3.Property<Guid>("PartialExpenseId")
                                                .HasColumnType("uuid");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 2)
                                                .HasColumnType("numeric(18,2)")
                                                .HasColumnName("amount");

                                            b3.HasKey("PartialExpenseId");

                                            b3.ToTable("partial_expenses");

                                            b3.WithOwner()
                                                .HasForeignKey("PartialExpenseId");
                                        });

                                    b2.Navigation("Amount")
                                        .IsRequired();

                                    b2.Navigation("Category");
                                });

                            b1.Navigation("Expenses");
                        });

                    b.OwnsOne("BudgetControl.Domain.ValueObjects.CyclePeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("BudgetCycleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EstimatedDurationInDays")
                                .HasColumnType("integer")
                                .HasColumnName("estimated_duration_days");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("BudgetCycleId");

                            b1.ToTable("budget_cycles");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCycleId");
                        });

                    b.Navigation("Days");

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("TotalCapacity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
