// <auto-generated />
using System;
using BudgetControl.Infrastructure.EF.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetControl.Migrations.Migrations
{
    [DbContext(typeof(BudgetControlDbContext))]
    [Migration("20260119235412_AddDomainEventStore")]
    partial class AddDomainEventStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BudgetControl.Domain.Aggregates.BudgetCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundingSourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FundingSourceId");

                    b.ToTable("budget_cycles", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Domain.Entities.FundingSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("funding_sources", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Infrastructure.EF.Persistence.EventStore.StoredDomainEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.ToTable("DomainEvents", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Domain.Aggregates.BudgetCycle", b =>
                {
                    b.HasOne("BudgetControl.Domain.Entities.FundingSource", "Source")
                        .WithMany()
                        .HasForeignKey("FundingSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetControl.Domain.ValueObjects.Money", "TotalCapacity", b1 =>
                        {
                            b1.Property<Guid>("BudgetCycleId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("total_capacity");

                            b1.HasKey("BudgetCycleId");

                            b1.ToTable("budget_cycles");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCycleId");
                        });

                    b.OwnsMany("BudgetControl.Domain.Entities.DayAllocation", "Days", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("BudgetCycleId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("TEXT")
                                .HasColumnName("date");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("INTEGER")
                                .HasColumnName("is_closed");

                            b1.HasKey("Id");

                            b1.HasIndex("BudgetCycleId");

                            b1.ToTable("day_allocations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BudgetCycleId");

                            b1.OwnsMany("BudgetControl.Domain.Entities.PartialExpense", "Expenses", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("DayAllocationId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(600)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("description");

                                    b2.HasKey("Id");

                                    b2.HasIndex("DayAllocationId");

                                    b2.ToTable("partial_expenses", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("DayAllocationId");

                                    b2.OwnsOne("BudgetControl.Domain.ValueObjects.Money", "Amount", b3 =>
                                        {
                                            b3.Property<Guid>("PartialExpenseId")
                                                .HasColumnType("TEXT");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 2)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("amount");

                                            b3.HasKey("PartialExpenseId");

                                            b3.ToTable("partial_expenses");

                                            b3.WithOwner()
                                                .HasForeignKey("PartialExpenseId");
                                        });

                                    b2.Navigation("Amount")
                                        .IsRequired();
                                });

                            b1.Navigation("Expenses");
                        });

                    b.OwnsOne("BudgetControl.Domain.ValueObjects.CyclePeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("BudgetCycleId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("EstimatedDurationInDays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("estimated_duration_days");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("start_date");

                            b1.HasKey("BudgetCycleId");

                            b1.ToTable("budget_cycles");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCycleId");
                        });

                    b.Navigation("Days");

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("TotalCapacity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
